### ISSUE TITLE
Sales Order Improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1425]
- [x] ~~Partial shipment of certain line items, before order is "complete"~~ - Ref #2199
- [x] Add same part to order multiple times (e.g. partial or scheduled shipments)
- [ ] Add "Quotation" model - transforms into a sales order - https://github.com/inventree/InvenTree/issues/8289
- [x] ~~Add "Shipment" model~~ - Ref #2199
- [x] Implement "Sale Price" into sales order lines
- [x] Allow customization of sale price in quotation or sales order
- [x] Assign stock by serial number entry (https://github.com/inventree/InvenTree/issues/1418)
- [ ] Assign stock to sales order using barcode scanner
- [x] Add custom template for "delete line item" view - describe what will happen upon confirmation
- [x] Add "blank" line to sales order

**Comment by matmair** [comment]
@SchrodingersGat I think 'Blank' line is now fulfilled.

**Comment by miggland** [comment]
What's your plan on the "Quotation" model? How will this be different to the SalesOrder?

I have used this method in some cases, just by opening a sales order earlier than an order arrives, but not confirming it. I haven't come up with any missing functionality. IMO, a status of "Quotation" instead of "Pending" would be sufficient. Is there anything else?

**Comment by SchrodingersGat** [comment]
Closing out, outstanding issues are now covered elsewhere
