### ISSUE TITLE
Overview issue:  Pricing

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#1656]
This is a overview issue for reorganising all pricing bits in InvenTree. Its goal is to focus all discussion into this issues (like #1577, #1645)

# Vision
A single page for all things pricing.
The following questions :
How much does it cost to buy the part from my registerd suppliers? How much does the BOM cost? How much do the different BOM-items contribute to the cost? For how much is it (internally in a BOM of an other part or externally) sold? How does the spread of these prices develop over different quantities?

# Tasks / Issues
## 1. Functional / API-updates
- [x] 1.1 Internal prices - as mentioned in #1606 - PR already in #1634
- [ ] 1.2 global and part-level sale-margins (with settings to enable - off by default) -> *up for discussion*
- [ ] 1.3 alerts for adjusting sale and internal prices if the purchase prices or margins change

## 2. UI - Updates
- [x] 2.1 just one view for all price breaks of a part - PR #1712 
- [x] ~~2.2 graph for showing stock prices (the purchase prices at which current stock was bought)  ->already present - maybe refactor *up for discussion*~~
- [x] 2.3 graph for buying and selling price ranges in different quantities
- [ ] 2.4 margin calculating assistant as in #1592 - calculates how much margin is present / adjust internal and sale pricing to keep margin

## 3. Ancelary stuff
- [x] 3.1 #391 show prices in ordering forms - PR #1657 / #1682
- [ ] 3.2 #1631 minimum order quantity for supplier parts
- [ ] 3.3 sale order total and adding a global weight for shiping, handeling etc (maybe also helpful for the question in #1592) - PR #1730
- [x] 3.4 docs for pricing
~~- [ ] 3.5 permissions to limit shown information~~ not necessary

**Comment by matmair** [comment]
@eeintech do you have any input on this? Especially 1.2, 2.2
I will first work on 3.1, 1.1, 2.1, 2.3, 1.2 in this order

**Comment by matmair** [comment]
Suggested merging order: #1588, #1657, #1645, #1634

**Comment by sintech** [comment]
Let me give a view from my perspective. 
I tend not to use PO for adding new stock, so for me the only way to keep pricing info is `purchase_price` in `stockitem`, so what @matmair did in #1577 is a very good improvement. What I still missing is a unit price in Stock table.
Speaking of PO, It wold be nice to have "Total" column with quantity * unit price and "Grand Total" row with sum of all rows quantity and prices.

**Comment by matmair** [comment]
@sintech thank you for your feedback! Please open issues for things you would like to see.

**Comment by eeintech** [comment]
@matmair Thanks for a stab a the pricing structure. I don't really have an opinion on 1.2 and 2.2 sorry.
The only thing I'm concerned is about the complexity of pricing in general. If there are too many pricing inputs and places it can be set, it raises the level of entry for anybody starting to use InvenTree.
What I think would be the real deal is if all the price data was stored and accessible in the same place.

If each stock item is connected to a supplier part, then the supplier part view would be best to manage it. It could have two tabs: "Supplier Price Break" and "Purchase Prices". The former view would just be the list of price breaks and the later would be the list of stock items associated to that supplier part and their purchase price. Purchase prices could be set there directly, same as the price breaks except it has only one unit price per stock item.

Then to view the part pricing, it would have single view where price is extracted from the supplier part pricing: both from price break and purchased price. User could have the option to calculate a part or BOM price based on either pricing source.

As I'm trying to cover only a relatively simple use-case my proposed structure may be missing what this issue is intended for. However simplicity is always a key point to any software so I would really love to see InvenTree stay as easy-to-use as possible :smiley:

**Comment by matmair** [comment]
@eeintech thanks for the feedback. I removed 2.2 from the plan.
I think that one place per part for all pricing should make it a lot easier. I also intend to add more information about all attributes into the view itself. I will submit a PR showing that after my PR backlog clears a bit up because a lot of the functionally I want to use in modals etc. is already in PRs and cross-referencing them makes merging more complex.

> If each stock item is connected to a supplier part, then the supplier part view would be best to manage it. It could have two tabs: "Supplier Price Break" and "Purchase Prices". The former view would just be the list of price breaks and the later would be the list of stock items associated to that supplier part and their purchase price. Purchase prices could be set there directly, same as the price breaks except it has only one unit price per stock item.

Adding additional points to add purchase prices is not covered by this proposal but seems to be a good idea 👍. This is not really covered by my workflows.

> Then to view the part pricing, it would have single view where price is extracted from the supplier part pricing: both from price break and purchased price. User could have the option to calculate a part or BOM price based on either pricing source.

Exactly that is the idea with 2.1: in one view every kind of price should be shown and all price breaks can be manipulated with all data at hand.

> As I'm trying to cover only a relatively simple use-case my proposed structure may be missing what this issue is intended for. However simplicity is always a key point to any software so I would really love to see InvenTree stay as easy-to-use as possible 😃

I think merging 2 or 3 tabs into one and adding graphs to show how the price-breaks compare to each other should achieve that. Also, there are setting-switches in mostly all of my functional additions so the starter-product keeps a low profile but supports more advanced needs.

**Comment by matmair** [comment]
@SchrodingersGat would appreciate your opinion when you have time.

**Comment by SchrodingersGat** [comment]
@matmair @eeintech I really appreciate the efforts you guys are putting in here on pricing.

I think there is a real worry that the pricing "complexity" will expand too much unless we are very clear on what functionality we should want, and where it should live.

In the following I will try to stick to these definitions:

- **Cost** - The theoretical amount of money required to pay for something
- **Price** - The *actual* amount of money paid

As far as I can tell, the following "pricing" information could be conceived:

| Price | Description | Linked to |
| --- | --- | --- |
| **Supplier Cost** | How much it costs to theoretically purchase a part from a given supplier | Supplier |
| **Purchase Price** | Historical pricing information for parts *actually purchased* | Stock Item / Purchase Order |
| **Internal Cost** | How much a part *costs* to make | Part |
| **BOM Cost** | Total cost for an assembly (total cost of component items) | Part |
| **Sale Cost** | How much a salable item is sold for (with cost-breaks) | Part |
| **Sale Price** | How much an item was actually sold for | Sales Order |

*(Are there any more? Please let me know if I've missed any...)*

This is already pretty complicated!

## Pricing Tab

I think that most of this information should / could be available on the Part *Pricing* tab, optionally rendered in the template based on the properties of the Part.

### Supplier Cost

If the part is *Purchasable* then a display of the supplier cost (at various quantities). Perhaps an input box for calculating the best "cost" at a particular quantity?

### Purchase Price

Historical record of pricing information for this part. Potentially very complex, as has to be sourced from Purchase Orders, or manual Stock Item creation, or both!

*Note: I'm happy to drop this one for now, as it is potentially very complicated and expands the scope too much*

### Internal Cost

Ref: https://github.com/inventree/InvenTree/pull/1634

Some parts may have associated internal costs which can be displayed here at various price breaks.

### BOM Cost

If a Part is an *Assembly* then we can display "BOM price" information here. Perhaps an input form for calculation of BOM cost at various price breaks? 

*Note: This calculation tool already exists as a modal window, but really needs some work!*

### Sale Cost

Sale price breaks are already supported - a graph of these (for *Saleable* parts) would be nice here.

### Sale Price

Historical sale price information. This should be generally easier than "Purchase Price" history as we just need to look at SalesOrder entries, which should not be deleted from the database like StockItem objects are.

===================================================================

In terms of simplicity I like the idea of all the "pricing" information being available on the one page. What is actually *on* the page should depend on the properties of the part.

There are a few outstanding PRs which need to be addressed in separation before such a pricing page could exist, but I think it's important to discuss what that page might look like while we work on individual features.

Also the documentation will need to follow suit. In the very least we need to ensure that our definitions are clear and consistent!

**Comment by matmair** [comment]
@SchrodingersGat sounds like we have the same idea of what it should be like.
Regarding internal price:

> **Internal Cost** 	How much a part _costs_ to make 	Part

I would more think of it as a override to BOM cost - if present - to include machining-cost and labour.

I will do a simple cosmetic mock-up to show how I would do it.
The PRs drift away from master further and further and for some of the functions I would depend on running PRs. Pulling them into the new branch will make merging more complicated. So just a few screenshots for discussing the UI.

**Comment by SchrodingersGat** [comment]
A single view for pricing is certainly needed: the current arrangement is becoming quite complicated!

![image](https://user-images.githubusercontent.com/10080325/122351512-8b58eb00-cf91-11eb-9b23-a2055b0602d6.png)

**Comment by SchrodingersGat** [comment]
As a simple example, here's the "new" (https://github.com/inventree/InvenTree/pull/1316) *Allocation* tab for the *Part* display, which shows (separately) both sales order allocations and build order allocations:

![image](https://user-images.githubusercontent.com/10080325/122539170-a3506d80-d06a-11eb-951d-de0ea8c66147.png)

Perhaps a similar approach for the pricing tab?

**Comment by eeintech** [comment]
@SchrodingersGat That would surely be a step in the right direction!

**Comment by Guusggg** [comment]
@matmair @eeintech 

Hi,

Today when implementing a barcode feature I notice that it's not possible to set the price for a StockItem through the API. The price is being copied from a PurchaseOrder but the API simply does not update it when sending an `update` for StockItem with keys `"purchase_price"` and `"purchase_price_currency"`. The Flutter API does return `true`, so it might seem the price is updated, however this is not reflected on the website. 

Is this issue on my side only or is it something that I can be working on in the near future?

Kind regards,

**Comment by matmair** [comment]
@Guusggg made a new issue for this-> this issue is intended as an overview.
