### ISSUE TITLE
[FR] Import tool refactor

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3101]
**Is your feature request the result of a bug?**
#2341
#3098
#3097 
#6321

**Problem**
We have several ways to do imports - we should refactor imports out.

**Suggested solution**
Two principles:
- API first
- backend-run first

Backend:
- [x] Switch to [data-wizard](https://github.com/wq/django-data-wizard)
- [x] Refactor all import code into a seperate app
- [x] Clean up / limit exposed APIs from data-wizard
- [x] Create backend worker for django-q
- [x] Create frontend that consumes the new APIs to build up an import flow

Refactor code base
- [x] Refactor BOM importer #3097
- [x] Refactor PO importer #3098
- [x] Refactor SO importer
- [x] Refactor Part importer

Unit tests:
- [ ] E2E Tests for import flow
- [ ] E2E for all refactored importers based on static import files that are in git

**Describe alternatives you've considered**
We should fix this, not sure what release to target though.

**Do you want to develop this?**
Yes - this will be something for the whole team I think.

-----------------------------------------------------

### Outstanding Tasks

- [x] Support "default values" when importing dataset
- [ ] Allow user to navigate back to previous data steps
- [ ] Add unit test for cleanup backup task
- [x] Ensure user has correct permissions before creating a new import session
- [x] Expose import / export functions to plugins
- [x] Allow plugins to define custom export fields / processes
- [ ] Allow bulk data export action to django admin interface
- [x] Replace existing "BOM Import" tool with new importer
- [x] Replace existing "BOM export" tool with new exporter
- [x] Replace existing "part import" tool with new importer
- [x] Replace existing "purchase order import" tool with new importer
- [x] Remove `django-import-export` framework entirely
- [ ] Allow bulk "update" via import (override current records, not create new ones)
- [x] Remove all custom import UI template code (html templates, legacy)
- [x] Check that all existing "django-import-export" models are covered by new framework
- [x] Show "original row data" for each row when importing data
- [ ] Allow user to create new related model "in place"
- [x] Add "context specific" importers for particular tables, rather than just in the admin center
- [x] Improve efficiency of data import process (currently takes ~1 minute for 1,000 records)
- [x] Impove user interface for data import - in particular, react hook efficiency
- [x] Enable per-column specification of "default" values in the admin portal
- [x] Documentation for new data import process

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/3101">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/3101/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/3101/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
This one feels like a high priority once we've got the current backlog of devops stuff out of the way

**Comment by lukasbrchl** [comment]
Hi @SchrodingersGat, would it please be possible to have at least the basic functionality of the import tool fixed for 0.8.0? I mean just import the parts from CSV and create orders from them as we had before. I know there is a lot of work for this, but this functionality is really important fur us. Thanks!

**Comment by SchrodingersGat** [comment]
Hi @lukasbrchl nothing planned at this stage but maybe your company would be willing to sponsor some development time on this? Please reach out to me if this would be an option for you.

**Comment by matmair** [comment]
@SchrodingersGat this will be important for #3901 / #2789 - our current functionality is not set up to work through the API so it can not be easily decoupled from the integrated frontend

**Comment by SchrodingersGat** [comment]
Yep, the import tool definitely needs to work via the API :)

**Comment by matmair** [comment]
Would be easier once #4304 is done as there is already a worker for celery.

**Comment by matmair** [comment]
https://www.reddit.com/r/InvenTree/comments/1410bvf/bulk_part_import/

**Comment by SchrodingersGat** [comment]
@matmair are you happy to close this one out? I think that functionally it has mostly been addressed - happy to wait for https://github.com/inventree/InvenTree/pull/9096 to be merged first though

**Comment by matmair** [comment]
Sure, go ahead!
