### ISSUE TITLE
[Epic] Approvals

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#5097]
This is a follow-up to #3501 which only required a simple flow. The following items should be relatively easy to implement - if the need for them arises. The code base was designed with them in mind.

```[tasklist]
### Rules
- [x] min number of approvers
- [x] max number of deniers
- [ ] quorum
- [ ] user attribute-based rules
- [ ] time limits on cases
```

```[tasklist]
### Workflow optimisation
- [ ] dynamic template selector
- [ ] revocation/removal of approvals
- [ ] interactive slack/teams messages
- [ ] invite/request approval
- [ ] template import/export
```

```[tasklist]
### Advanced feature
- [ ] rule templates
- [ ] events/tracking of any changes (see stock tracking)
- [ ] notifications for approvals
```

These features could be very interesting for Change Managment / ECO / ECR and maybe also for usage in plugins.

**Comment by SchrodingersGat** [comment]
@matmair thanks for taking the time to plan for these features and implement them here

**Comment by matmair** [comment]
Those are mostly implemented in my plugin [inventree_approval](https://doc.invenhost.com/inventree_approval/main/home/)
