### ISSUE TITLE
Platform UI

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#5212]
Overview for the porting of classic UI to Platform UI. Follow up to #3901 #2789

```[tasklist]
### Workflows
- [x] Run unit tests as part of CI #5011
- [x] Code coverage integration with coveralls
- [x] Enforce code styling (including comments) for tsx code
- [x] Run code style checks as part of CI #5011
- [x] Release: Docker #5011
- [ ] #5277
- [ ] https://github.com/inventree/InvenTree/issues/5278
- [ ] https://github.com/inventree/InvenTree/issues/5282
```

```[tasklist]
### Backend
- [x] Add SPA helpers #5011
- [x] Remove custom redirects #5011
- [x] Simple login #5209 #5207
- [x] Save ui settings https://github.com/inventree/InvenTree/pull/5343
- [ ] https://github.com/inventree/InvenTree/issues/6389
- [ ] https://github.com/inventree/InvenTree/issues/3101
```

```[tasklist]
### Docs
- [x] Frontend architecture
- [x] Code structure
- [x] Getting started for frontend
- [x] Component docs (maybe storybook)
```

```[tasklist]
### Frontend base
- [x] Navigation #5207
- [x] Mega menu #5207
- [ ] https://github.com/inventree/InvenTree/issues/5323
- [x] URL/navigation structure #5207
- [x] Base page layout
- [x] Detail page layout
- [ ] https://github.com/inventree/InvenTree/issues/5354
- [ ] #5218
- [x] Barcode Scanning #5207
- [x] Notifications
- [ ] https://github.com/inventree/InvenTree/issues/5345
- [ ] https://github.com/inventree/InvenTree/issues/6283
- [ ] https://github.com/inventree/InvenTree/issues/6282
- [x] Social Login #5753
- [x] Social Registration #5753
- [ ] #5296
- [ ] https://github.com/inventree/InvenTree/issues/5888
- [ ] #5755
- [ ] https://github.com/inventree/InvenTree/issues/6285
- [ ] https://github.com/inventree/InvenTree/issues/6813
- [x] [PUI] Switch to native Tree component - https://mantine.dev/core/tree/#example-files-tree
- [ ] https://github.com/inventree/InvenTree/issues/7920
```

```[tasklist]
### Frontend pages
- [ ] https://github.com/inventree/InvenTree/issues/5324
- [x] User settings management #5016
- [x] Global settings management #5016
- [x] Part
- [x] Part Category
- [x] Stock Item
- [x] Stock Location
- [x] Company
- [x] Supplier Part
- [x] Manufacturer Part
- [x] Build Order
- [x] Purchase Order
- [x] Sales Order
- [x] User Managment #5016
- [x] All "part" functions - https://github.com/inventree/InvenTree/issues/6022
- [x] All "stock" functions
- [x] All "build order" functions
- [x] All "sales order" functions
- [x] All "return order" functions
- [x] All "purchase order" functions
- [ ] https://github.com/inventree/InvenTree/issues/7026
```

```[tasklist]
### Plugins
- [x] APIs for rendering plugins in UI - https://github.com/inventree/InvenTree/pull/7470
- [x] Plugin settings screen #5016
- [x] New / Refactor "Panel Mixin" support - https://github.com/inventree/InvenTree/pull/7470
- [ ] https://github.com/inventree/InvenTree/issues/5269
```

```[tasklist]
### Needs to be handled before next stable - follow-ups
- [x] Follow up to https://github.com/inventree/InvenTree/pull/5325 - Add tables
- [x] Allow to hide the server selector and configure custom server via Django settings #5343 @wolflu05
- [ ] https://github.com/inventree/InvenTree/issues/6554
- [ ] https://github.com/inventree/InvenTree/issues/5452
- [ ] https://github.com/inventree/InvenTree/issues/7869
```

```[tasklist]
### In the future (tm) - follow-ups
- [ ] After deprecating the old ui move the new ui to `/`. @wolflu05
- [ ] https://github.com/inventree/InvenTree/issues/7347
```

**Comment by matmair** [comment]
@SchrodingersGat I added the issues/PR that currently cover the code sections

**Comment by wolflu05** [comment]
```[tasklist]
# ... Addition to above
- [ ] Allow to hide the server selector and configure custom server via Django settings #5343
- [ ] Add links to the new ui in the old ui like `try this out in the new ui`
- [ ] After deprecating the old ui move the new ui to `/`.
```

**Comment by matmair** [comment]
As part of https://github.com/inventree/InvenTree/pull/6543 / https://github.com/matmair/InvenTree/pull/174 I have tried to factor out and remove CUI to discover dependencies between REST API, CUI and tests. Overall we are pretty good decoupled, there are a few tests that need to be rewritten - which I have marked with TODOs.
One pretty important thing is import/export functionality, which is very much PUI-dependent right now - what is your reading on that @SchrodingersGat?

**Comment by SchrodingersGat** [comment]
@matmair my two major priorities after the pending `0.14.0` release are:

- Implement the pending code refactor PR
- Assess import / export project

**Comment by matmair** [comment]
Suggested additions for 1.0 or beyond:

- Add permissions view/edit to groups
- Add public "profile" pages for users/groups with basic info about the object
- Add hover cards for users/groups and link to profile wherever user/groups are shown/listed
- Make the dashboard more helpful: 
  - Add per-user customisable widget selection
  - Add option to add all tables with saved queries
  - Add "metrics" widget that shows just count for query
  - Add "quick-action" widget
  - Add "current time" widget
  - Add link-to-item widget
- Add rich search to user and systemsettings, admin center
- Add per-page quick-jump to different panels on the page to spotlight
- Add all actions on page per-page to spotlight

**Comment by BryanJacobs** [comment]
The "Part" page is marked as complete, but it seems to be missing the ability to download a part image from a URL.

I don't see a tracker for that feature here :cry: .

**Comment by institutohidraulica** [comment]
On the PUI I miss the option to "Return to Stock" for a stock item assigned to a customer, while was working perfeclty on the CUI
![Image](https://github.com/user-attachments/assets/19e22435-7c0c-4c57-bd6c-ac8e0a75cad6)
![Image](https://github.com/user-attachments/assets/c348fbfa-e1c7-4013-97e6-0874c5debea7)

**Comment by matmair** [comment]
@BryanJacobs  @institutohidraulica please open either disucssions in https://github.com/inventree/InvenTree/discussions/5328 or new issues; this epic is for tracking open work

**Comment by SchrodingersGat** [comment]
@matmair @wolflu05 I think that all that is still remaining on this EPIC is to remove the `/platform/` prefix from the routing?

**Comment by matmair** [comment]
@SchrodingersGat I do not think we should implement this with the switch to 1.0 as that will lead to a lot of broken links. IMO there is a need to build some kind of translation layer between old and new links. I used to have the CUI links in the ModelInformationDict but that seems to have been removed - so something similar has to be re-engineered to not break a lot of links.

**Comment by SchrodingersGat** [comment]
@matmair ok let's work out a way forward then - I would like to see the prefix removed if possible. The ModelInformationDict is a good idea for a translation layer, looks like I have culled those (sorry)!

Should we look to remove the prefix entirely, or replace it with something generic like 'web'?

**Comment by SchrodingersGat** [comment]
> I used to have the CUI links in the ModelInformationDict but that seems to have been removed

Ok, looks like this was removed as part of your PR to "Remove CUI": https://github.com/inventree/InvenTree/pull/8384/files#

![Image](https://github.com/user-attachments/assets/152bc6b5-b3e0-44da-8247-7acecc41eb4b)

**Comment by SchrodingersGat** [comment]
@jacobfelknor if you think there are functionalities missing from the new interface please raise them individually in new issues so we can track them :)

**Comment by SchrodingersGat** [comment]
I am going to close this out, the new UI is functionally pretty much complete, certainly all of the major tasks outlined here have been implemented. Well done everyone involved!
