### ISSUE TITLE
[Roadmap] Plugin Improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5645]
From issues identified in https://github.com/inventree/InvenTree/pull/5624

### Plugin Features / Improvements

```[tasklist]
### Plugin Tasks
- [ ] Fix bug in "install plugin" API endpoint where failure is not correctly reported
- [ ] Automatically reload plugin registry when plugins change in another running worker
- [ ] Automatically run migrations when a new plugin is activated
- [ ] Collect more metadata for plugins which are not installed
- [ ] Improve plugin reload mechanism with mutex locking
- [ ] Enable plugin list API to be filtered by "builtin" or "sample" status
```

**Comment by matmair** [comment]
Not sure collection of more metadata is possible without running into serious security problems.

**Comment by SchrodingersGat** [comment]
> Not sure collection of more metadata is possible without running into serious security problems.

It may not be. I'd like to look into it but it doesn't look likely

**Comment by matmair** [comment]
Would be amazing if there were a way, I am just not aware of one.

**Comment by wolflu05** [comment]
If there is no other way, the only thing I see is parsing the setup.py without executing it, by converting it to an AST with pythons ast module.

**Comment by 30350n** [comment]
> If there is no other way, the only thing I see is parsing the setup.py/plugin file without executing it, by converting it to an AST with pythons ast module.

This is exactly how [Blender does it](https://github.com/blender/blender/blob/9c0bffcc89f174f160805de042b00ae7c201c40b/scripts/modules/addon_utils.py#L76) for Python addons. Each addon has to contain a static `bl_info` section, like [this for example](https://github.com/30350n/pcb2blender/blob/master/pcb2blender_importer/__init__.py#L1), which can be parsed like that. The actual addon code will only be executed once you enable the addon.

**Comment by SchrodingersGat** [comment]
@30350n thanks for the info! And very nice looking plugin too. Might have to use that myself
