### ISSUE TITLE
[PUI] SSO Support

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5753]
Add SSO for the new interface:

```[tasklist]
### Tasks
- [x] Expose SSO information to the API
- [x] Add SSO options to login screen
- [x] SSO login returns a token (and then normal operations after that)
- [x] Add SSO configuration to system settings pages
- [x] Add login taint
```

**Comment by matmair** [comment]
@SchrodingersGat I would split out settigns into a seperate issue, they are very different APIs
