### ISSUE TITLE
[React] Implement existing Part functions

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6022]
Ref: https://github.com/inventree/InvenTree/issues/5212

This issue serves as a list of functions / items / views which need to be reimplemented for the new react interface, specifically for the "part" views

### TODO

- [x] Implement part overview page
- [x] Implement part category page
- [ ] Implement "part detail" panel
- [ ] Implement "select part image" interface
- [ ] Implement "parametric part table"
- [ ] Implement "allocations" panel
- [ ] Implement "pricing" panel
- [ ] Implement "manufacturers" panel
- [ ] Implement "scheduling" panel
- [ ] Implement "stocktake" panel
- [ ] Implement "purchase orders" panel
- [ ] Implement "duplicate part" function
- [ ] Implement "order part" functionality
- [ ] Implement "label printing" functionality

**Comment by matmair** [comment]
@SchrodingersGat do you have a screenshot of what from CUI exactly is missing?

**Comment by SchrodingersGat** [comment]
I think that the only major missing component currently is the "order parts" wizard
