### ISSUE TITLE
Possible breaking changes for 1.0

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#6417]
With somewhat soon (once #5212 is done) 1.0 approaching, we can start thinking about breaking changes we might want to implement to make long-term maintainability easier.

```[tasklist]
### Tasks
- [ ] https://github.com/inventree/InvenTree/issues/5015
- [ ] https://github.com/inventree/InvenTree/issues/5578
- [ ]  moving config files out of the code source
- [ ] do not require any envs on docker startup, assume local subfolder /data
- [ ] rename default python `env` to `.venv`
- [ ] respect AUTH_USER_MODEL
```

See also this discussion https://github.com/inventree/InvenTree/pull/6173#issuecomment-1928113213

**Comment by matmair** [comment]
Thoughts @inventree/maintainer @inventree/triage

**Comment by matmair** [comment]
Open to more ideas if others arise

**Comment by matmair** [comment]
Another point of discussion: rename the latest branch from `master` to `main`. The latter becomes more and more the default and I think that it also is the more logical naming. Thoughts @SchrodingersGat?

**Comment by SchrodingersGat** [comment]
> Another point of discussion: rename the latest branch from `master` to `main`. The latter becomes more and more the default and I think that it also is the more logical naming. Thoughts @SchrodingersGat?

Not opposed to that

**Comment by SchrodingersGat** [comment]
@matmair what are your thoughts on this one? Do you want to complete any of the remaining points before we release `1.0.0`?

**Comment by matmair** [comment]
I think it would be unwise to do any of them so shortly before release of a stable. We can always tackle them later.
