### ISSUE TITLE
[PUI] Part Pricing Improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6999]
Follows on from https://github.com/inventree/InvenTree/pull/6985

### Tasks

- [x] Add button to reload / rebuild part pricing
- [x] Add dialog to edit manual pricing overrides
- [ ] Split pricing history into separate panel tab potentially
- [ ] Add separate permissions RuleSet for viewing pricing data

**Comment by SchrodingersGat** [comment]
Closing this, merging with https://github.com/inventree/InvenTree/issues/7025
