### ISSUE TITLE
[PUI] Part Pricing Improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7025]
- Follow up to https://github.com/inventree/InvenTree/pull/6985

```[tasklist]
### TODO
- [x] click on a line in the overview and jump to the matching accordion (that should also open)
- [x] The data is displayed as decimal, not in local currency formatting. Can that be changed?
- [x] improve rendering of tooltip label data
- [x] Improve rendering of legend label data
- [x] only render accordions if there is data
- [ ] Split pricing history into separate panel tab potentially
- [ ] use a colour scheme generator like CUI - those red and green colours especially are a bit difficult for colour-blind users
- [ ] if iv. is implemented as a donut: a switch to render about and percental rendering
- [ ] Add separate permissions RuleSet for viewing pricing data
```

**Comment by matmair** [comment]
@SchrodingersGat should we merge this with https://github.com/inventree/InvenTree/issues/6999?
