### ISSUE TITLE
[Importer] Replace existing import workflows

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7572]
- New import workflow introduced in https://github.com/inventree/InvenTree/pull/6911
- There are still a number of "legacy" workflows in place
- These need to be replaced
- Likely only supported in the new react interface (PUI)

### Tasks
- [x] Replace existing "BOM Import" tool with new importer - https://github.com/inventree/InvenTree/pull/7635
- [x] Replace existing "BOM export" tool with new exporter - https://github.com/inventree/InvenTree/issues/8686
- [x] Replace existing "part import" tool with new importer
- [x] Replace existing "purchase order import" tool with new importer - https://github.com/inventree/InvenTree/pull/7671
- [ ] Remove `django-import-export` framework entirely - https://github.com/inventree/InvenTree/pull/8685
- [x] Add "context specific" importers for particular tables, rather than just in the admin center
- [ ] Remove all custom import UI template code (html templates, legacy) - https://github.com/inventree/InvenTree/pull/8685
- [ ] Check that all existing "django-import-export" models are covered by new framework

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/inventree) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/inventree/InvenTree/issues/7572">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/inventree/InvenTree/issues/7572/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/inventree/InvenTree/issues/7572/pledge.svg">
</picture>
</a>

**Comment by SchrodingersGat** [comment]
This is now sufficiently addressed with the closure of https://github.com/inventree/InvenTree/issues/8686
