### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8584]
### Body of the issue

Overhaul documentation for 1.0.0 release

### Tasks

- [ ] Replace all screenshots with new interface
- [ ] Ensure all new PUI features are documented
- [ ] Add general "user interface" documentation (how to use tables, etc)

**Comment by spyingcyclops** [comment]
Hi, I'd be interested in working on this

**Comment by SchrodingersGat** [comment]
@spyingcyclops fantastic, the more help the better! There are a lot of features and aspects which are currently either undocumented or in need of improvement!

Please lmk if you need any help getting setup to build the documentation locally!

**Comment by matmair** [comment]
@SchrodingersGat should we take another shot at auto-generating screenshots? I seem to remember you had a pretty promising OR for that.

**Comment by SchrodingersGat** [comment]
I can reopen that, but the amount of effort required to set it up seemed disproportionate. Compared to manually generating the screenshots

**Comment by matmair** [comment]
@spyingcyclops are you working on this / do you need assistance?

**Comment by spyingcyclops** [comment]
No, no capacity to work on it atm, thanks

**Comment by matmair** [comment]
no worries, thanks for the prompt response.

**Comment by SchrodingersGat** [comment]
Closing this out, the "general user interface" docs have now been implemented
