### ISSUE TITLE
[1.0.0] Reimplement old BOM exporter

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8686]
"New" BOM export tool only exports flattened BOM with minimal information.

For 1.0.0, this should be reimplemented to support the "old" export style which allows cascading exporting and inclusion of additional fields.

This could be implemented via a plugin, but we would need to allow the exporter interface to hook into the plugin ecosystem.

### TODO

- [x] Allow export of "multi level" BOM data
- [ ] Include "pricing" information in BOM export
- [ ] Include "parameter" information in BOM export
- [ ] Include "stock" information in BOM export
- [ ] Include "supplier" information in BOM export
- [ ] Include "manufacturer" information in BOM export
- [x] Include "substitute" information in BOM export

### References

- https://github.com/inventree/InvenTree/pull/8685
- https://github.com/inventree/InvenTree/pull/9096

### Note

As part of this PR, remove the entirety of `./src/backend/InvenTree/part/bom.py`

**Comment by matmair** [comment]
@SchrodingersGat I think plugins should be a second step, that introduces features that were not there before.
